all: FFEA_extract_specific_nodes.c FFEA_extract_positions.c
	gcc -Wall -lm -O3 FFEA_extract_specific_nodes.c -o FFEA_extract_specific_nodes
	gcc -Wall -lm -O3 FFEA_extract_positions.c -o FFEA_extract_positions
debug:
	gcc -Wall -lm -g FFEA_extract_specific_nodes.c -o FFEA_extract_specific_nodes
