all:
	g++ emdb_map_to_ffea.c -O3 -Wall -lm -o emdb_map_to_ffea
	g++ add_maps.c -O3 -Wall -lm -o add_maps
	g++ convert_pdb_to_emdb_map.c -O3 -Wall -lm -o convert_pdb_to_emdb_map
debug:
	g++ emdb_map_to_ffea.c -g -Wall -lm -o emdb_map_to_ffea
	g++ add_maps.c -g -Wall -lm -o add_maps
	g++ convert_pdb_to_emdb_map.c -g -Wall -lm -o convert_pdb_to_emdb_map
